/**
 * Research ▸ Study: the steered flow. You pick the asset and the question;
 * the AI picks the related assets and the checks, says why for each, and
 * explains the result. Anything it adds, you can switch off.
 *
 * NOT A SECOND ENGINE. Every control here writes the same `StudySpec` the
 * four-step Analyse stepper edits, through the same `StudyState`, and "Run
 * research" is the same `state.run()`. The stepper is still one click away
 * ("Every setting") for anyone who wants roles, windows and the full method
 * catalogue — this is the same study with the choices a first-time operator
 * does not need folded away, not a simplified copy that could disagree with it.
 *
 * WHAT "AI" MEANS ON THIS PAGE
 * The related assets come from a declared relationship map
 * (`study/related.ts` over `data/drivers.ts`) and the checks from a declared
 * question table (`study/question.ts`). The explanation is assembled from the
 * report (`study/explain.ts`). Nothing is generated by a language model and
 * nothing is invented: a figure appears only once a run has measured it.
 */

import { h, type Child } from "../dom";
import { computed, renderEffect, type ReadSignal } from "../../core/signal";
import { pkWhy } from "../panelkit";
import { whoTag, type Who } from "../today/card";
import { blocking, costsOf, foldsOf, HISTORY_YEARS, MAX_FOLDS, MIN_FOLDS, yearsLabel, type HistoryYears } from "../../study/spec";
import { inputsFor, methodsFor, questionLabel, QUESTIONS, type QuestionId } from "../../study/question";
import { availability, METHOD_BY_ID } from "../../study/methods";
import { durationLabel } from "../../study/plan";
import { explainReport } from "../../study/explain";
import { sourceOf } from "../../study/related";
import { DEFAULT_COSTS } from "../../backtest/engine";
import type { StudyState, StepId } from "../study/state";

export interface SteeredOptions {
  /** The chart's symbol, offered as the first quick pick. */
  readonly chartSymbol: ReadSignal<string>;
  /** Open the four-step stepper, at a step. */
  readonly openFull: (step: StepId) => void;
}

/** Quick picks after the chart's own symbol — one per asset class the map covers. */
export const QUICK_ASSETS: readonly string[] = ["BTCUSDT", "ETHUSDT", "XAUUSD", "EURUSD", "SPX500"];

/** The timeframes and depths the design offers; the current value is always kept. */
const TIMEFRAMES = ["1h", "4h", "1d"] as const;
const DEPTHS: readonly HistoryYears[] = [1, 2, 5];

function card(title: string, who: Who, whoText: string, cls: string, ...body: Child[]): HTMLElement {
  return h(
    "section",
    { class: `dd-panel rs-card ${cls}`, "data-who": who },
    h("header", { class: "rs-card-head" }, h("h2", { class: "rs-card-title", text: title }), whoTag(who, whoText)),
    ...body,
  ) as HTMLElement;
}

function field(label: string, control: HTMLElement, note?: Child): HTMLElement {
  return h("label", { class: "rs-field" }, h("span", { class: "rs-field-label", text: label }), control, note ?? null) as HTMLElement;
}

const pct = (v: number): string => `${Math.round(v * 100)}%`;

export function createSteeredStudy(state: StudyState, opts: SteeredOptions): HTMLElement {
  const { spec } = state;

  /* ── 1 · Your asset ─────────────────────────────────────────────────── */

  const assetInput = h("input", {
    class: "rs-input mono",
    type: "text",
    spellcheck: "false",
    "aria-label": "Asset to study",
    value: () => spec().symbol,
    onchange: (e) => state.setAsset((e.target as HTMLInputElement).value),
  });

  const quick = h("div", { class: "rs-tags", role: "group", "aria-label": "Quick picks" });
  renderEffect(() => {
    const current = spec().symbol;
    const picks = [...new Set([opts.chartSymbol().toUpperCase(), ...QUICK_ASSETS].filter((s) => s !== ""))];
    quick.replaceChildren(
      ...picks.map((s) =>
        h("button", {
          class: "rs-tag mono",
          type: "button",
          "aria-pressed": s === current ? "true" : "false",
          text: s,
          onclick: () => state.setAsset(s),
        }),
      ),
    );
  });

  const assetCard = card("1 · Your asset", "you", "You", "rs-asset", field("Symbol", assetInput), quick);

  /* ── 2 · Your question ──────────────────────────────────────────────── */

  const questionSelect = h("select", {
    class: "rs-input",
    "aria-label": "What to predict",
    onchange: (e) => state.setQuestion((e.target as HTMLSelectElement).value as QuestionId),
  });
  renderEffect(() => {
    const s = spec();
    const current = state.question().id;
    questionSelect.replaceChildren(
      ...QUESTIONS.map((q) =>
        h("option", { value: q.id, text: questionLabel(q, s.horizon), selected: q.id === current ? "" : undefined }),
      ),
    );
    questionSelect.value = current;
  });

  const horizonInput = h("input", {
    class: "rs-input mono",
    type: "number",
    min: "1",
    step: "1",
    "aria-label": "Bars ahead",
    value: () => String(spec().horizon),
    onchange: (e) => {
      const v = Math.round(Number((e.target as HTMLInputElement).value));
      if (Number.isFinite(v) && v >= 1) state.patch({ horizon: v });
    },
  });

  const tfSelect = h("select", {
    class: "rs-input",
    "aria-label": "Timeframe",
    onchange: (e) => {
      const tf = (e.target as HTMLSelectElement).value;
      state.patch({ timeframe: tf, name: `${spec.peek().symbol} ${tf}` });
    },
  });
  renderEffect(() => {
    const tf = spec().timeframe;
    const list: string[] = [...TIMEFRAMES];
    if (!list.includes(tf)) list.push(tf);
    tfSelect.replaceChildren(...list.map((t) => h("option", { value: t, text: t, selected: t === tf ? "" : undefined })));
    tfSelect.value = tf;
  });

  const depthSelect = h("select", {
    class: "rs-input",
    "aria-label": "History",
    onchange: (e) => {
      const v = (e.target as HTMLSelectElement).value;
      const years: HistoryYears | null =
        v === "max" ? "max" : (HISTORY_YEARS.find((y) => String(y) === v) ?? null);
      if (years !== null) state.patch({ years });
    },
  });
  renderEffect(() => {
    const y = spec().years;
    const list: HistoryYears[] = [...DEPTHS];
    if (!list.includes(y)) list.push(y);
    depthSelect.replaceChildren(
      ...list.map((d) =>
        h("option", { value: String(d), text: d === "max" ? "All available" : `${yearsLabel(d).replace("y", "")} year${d === 1 ? "" : "s"}`, selected: d === y ? "" : undefined }),
      ),
    );
    depthSelect.value = String(y);
  });

  const questionCard = card(
    "2 · Your question",
    "you",
    "You",
    "rs-question",
    field("Predict", questionSelect),
    h("p", { class: "rs-note", text: () => state.question().answers }),
    h(
      "div",
      { class: "rs-grid3" },
      field("Bars ahead", horizonInput),
      field("Timeframe", tfSelect),
      field("History", depthSelect),
    ),
  );

  /* ── 4 · How strict + Run ───────────────────────────────────────────── */

  const rulesApply = computed(() => state.question().usesRules);

  const foldsOut = h("span", { class: "mono rs-out", text: () => String(foldsOf(spec())) });
  const foldsInput = h("input", {
    class: "rs-range",
    type: "range",
    min: String(MIN_FOLDS),
    max: String(MAX_FOLDS),
    step: "1",
    "aria-label": "Walk-forward test rounds",
    value: () => String(foldsOf(spec())),
    disabled: () => (rulesApply() ? undefined : ""),
    oninput: (e) => state.setFolds(Number((e.target as HTMLInputElement).value)),
  });

  const costBtn = (value: "standard" | "none" | "measured", text: string): HTMLElement =>
    h("button", {
      class: "seg-btn",
      type: "button",
      text,
      "aria-pressed": () => (costsOf(spec()) === value ? "true" : "false"),
      disabled: () => (rulesApply() ? undefined : ""),
      onclick: () => state.setCosts(value),
    }) as HTMLElement;

  const runnable = computed(() => {
    const bad = blocking(state.problems());
    if (bad[0] !== undefined) return { ok: false, why: bad[0].text };
    /* Before a fetch every method is blocked for want of rows, so an empty
       plan means nothing yet — `run()` fetches first and re-plans on what
       loaded. After a fetch, an empty plan is a real refusal and says why. */
    const plan = state.plan();
    if (state.checked() && plan.steps.length === 0) {
      return { ok: false, why: plan.refusal ?? "None of the chosen checks can run on the bars that loaded." };
    }
    return { ok: true, why: "" };
  });

  const runBtn = h("button", {
    class: "sy-run-btn rs-run",
    type: "button",
    text: () => (state.busy() ? state.progress() || "Running…" : "Run research"),
    disabled: () => (state.busy() || !runnable().ok ? "" : undefined),
    onclick: () => void state.run(),
  });

  const strictCard = card(
    "4 · How strict",
    "you",
    "You",
    "rs-strict",
    field("Walk-forward test rounds", foldsInput, foldsOut),
    field(
      "Costs",
      h("div", { class: "seg", role: "group", "aria-label": "Costs" },
        costBtn("standard", "Standard"), costBtn("measured", "My broker"), costBtn("none", "None")),
    ),
    h("p", {
      class: "rs-note",
      text: () =>
        rulesApply()
          ? "Applies to the rule tests: more rounds is a harder test, and None shows whether costs are the whole result."
          : "No rule is tested for this question, so rounds and costs change nothing here.",
    }),
    pkWhy(
      /* THE SENTENCE WAS TRUE AND STOPPED BEING TRUE. It said "nothing reads
         your broker's commission into a study yet", and v63.9 made the Playbook
         read the broker's measured SPREAD. A comment that has quietly become
         false is worse than one that was never written, because it reads as a
         checked fact — the class this project records as "a comment describing a
         control is not a control". Narrowed to what is still accurate: this desk
         charges the assumption, the Playbook can charge the measurement, and
         commission is read by neither. */
      `Standard costs are the backtest engine's model — ${(DEFAULT_COSTS.spread * 10_000).toFixed(0)}bp spread, ${(DEFAULT_COSTS.commission * 100).toFixed(2)}% commission a side, ${(DEFAULT_COSTS.slippage * 10_000).toFixed(0)}bp slippage. My broker charges the SPREAD your contract spec reports and keeps the other two at the assumption, because a commission is per-lot and account-specific and slippage belongs to the venue — neither is readable off an instrument. Standard stays the default and is usually the HARSHER one: measured against this account it is about 4.8x the real spread on gold, so a rule refused under it may clear the spread you actually pay. With no broker sync, My broker falls back to Standard rather than guessing. Each round trains on the bars before it and is scored on the bars after, with a gap between so the two cannot overlap.`,
      "Why?",
    ),
    runBtn,
    h("p", { class: "rs-block", text: () => (state.busy() ? "" : runnable().why) }),
    h("p", {
      class: "rs-note mono",
      text: () => {
        const plan = state.plan();
        if (!state.checked()) return `${spec().methods.length} check${spec().methods.length === 1 ? "" : "s"} chosen · bars are fetched when you run`;
        return `${plan.steps.length} check${plan.steps.length === 1 ? "" : "s"} · ${plan.hypotheses.toLocaleString()} hypotheses · about ${durationLabel(plan.estimateMs)}`;
      },
    }),
  );

  /* ── 3 · Related assets ─────────────────────────────────────────────── */

  const loadNote = (symbol: string): string => {
    const l = state.loads().find((x) => x.symbol.toUpperCase() === symbol.toUpperCase());
    if (l === undefined || l.state === "unchecked") return "measured on run";
    if (l.state === "loading") return "fetching…";
    if (l.state === "failed") return "no bars";
    if (l.state === "short") return `short · ${l.bars.toLocaleString()} bars`;
    return `${l.bars.toLocaleString()} bars${l.coverage === null ? "" : ` · ${pct(l.coverage)}`}`;
  };

  const relList = h("div", { class: "rs-rel-list" });
  renderEffect(() => {
    const rows = state.relatedList();
    if (rows.length === 0) {
      relList.replaceChildren(h("p", { class: "rs-empty", text: "No related assets. The study will use the asset's own history only." }));
      return;
    }
    relList.replaceChildren(
      ...rows.map((r) =>
        h(
          "div",
          { class: "rs-rel", "data-on": r.on ? "true" : "false", "data-who": r.who },
          h(
            "label",
            { class: "rs-rel-main" },
            h("input", {
              type: "checkbox",
              checked: r.on,
              "aria-label": `${r.on ? "Leave out" : "Include"} ${r.symbol}`,
              /* An operator's own addition has no proposal to fall back to,
                 so switching it off removes it — `setRelated` does both. */
              onchange: (e) => state.setRelated(r.symbol, (e.target as HTMLInputElement).checked),
            }),
            h("b", { class: "mono rs-rel-sym", text: r.symbol }),
            h("span", { class: "rs-rel-why", text: r.reason }),
            h("span", { class: "mono rs-rel-state", text: () => (r.on ? loadNote(r.symbol) : "off") }),
          ),
          pkWhy(r.why, "Why?"),
        ),
      ),
    );
  });

  const withheld = h("div", { class: "rs-withheld" });
  renderEffect(() => {
    const w = state.related().withheld;
    withheld.replaceChildren(
      ...(w.length === 0
        ? []
        : [
            pkWhy(
              w.map((x) => `${x.label}: ${x.reason}`).join(" "),
              `Left out (${w.length})`,
            ),
          ]),
    );
  });

  const addInput = h("input", {
    class: "rs-input mono",
    type: "text",
    spellcheck: "false",
    placeholder: "Add your own, e.g. NAS100",
    "aria-label": "Add a related asset",
    onkeydown: (e) => {
      if ((e as KeyboardEvent).key === "Enter") addOwn();
    },
  });
  const addNote = h("p", { class: "rs-note" });
  function addOwn(): void {
    const v = addInput.value.trim().toUpperCase();
    if (v === "") return;
    if (v === spec.peek().symbol) {
      addNote.textContent = `${v} is the asset being studied, so it cannot also be a related one.`;
      return;
    }
    state.addOwn(v);
    addInput.value = "";
    addNote.textContent =
      sourceOf(v) === null
        ? `Added ${v}. No source here is known to serve it — it will be tried when you run, and shown as "no bars" if nothing answers.`
        : `Added ${v}.`;
  }

  const relatedCard = card(
    "3 · Related assets — chosen by AI",
    "ai",
    "AI",
    "rs-related",
    h("p", { class: "rs-note", text: () => state.related().intro }),
    relList,
    withheld,
    h("div", { class: "rs-add" }, addInput, h("button", { class: "sy-ghost", type: "button", text: "Add", onclick: addOwn })),
    addNote,
    h("p", {
      class: "rs-note",
      text: () =>
        state.question().relatedRole === "measured" && spec().context.length > 0
          ? "For this question they are measured beside the asset, not fed into its checks."
          : "",
    }),
  );

  /* ── Inputs and models ──────────────────────────────────────────────── */

  const inputs = h("div", { class: "rs-tags" });
  renderEffect(() => {
    const s = spec();
    const list = inputsFor(s.methods, s.context.length, s.symbol);
    inputs.replaceChildren(...list.map((i) => h("span", { class: "rs-chip", title: i.why, text: i.label })));
  });

  const models = h("div", { class: "rs-tags", role: "group", "aria-label": "Checks that will run" });
  renderEffect(() => {
    const s = spec();
    const q = state.question();
    const ids = [...new Set([...methodsFor(q.id, s.context.length > 0), ...s.methods])];
    /* Availability WITHOUT the row count: before a fetch every method reads
       "no bars fetched yet", which is true and says nothing about this
       method. What is worth showing now is what no fetch can fix — a
       missing library, or a check that needs a series marked Driver. */
    const ctx = { ...state.methodCtx(), checked: true, rows: Number.MAX_SAFE_INTEGER };
    models.replaceChildren(
      ...ids.flatMap((id) => {
        const m = METHOD_BY_ID.get(id);
        if (m === undefined) return [];
        const a = availability(m, ctx);
        const on = s.methods.includes(id);
        return [
          h("button", {
            class: "rs-tag",
            type: "button",
            "aria-pressed": on ? "true" : "false",
            "data-blocked": a.state === "blocked" ? "true" : "false",
            title: a.state === "blocked" ? a.reason : m.blurb,
            text: m.label,
            onclick: () => state.toggleMethod(id, !on),
          }),
        ];
      }),
    );
  });

  const modelsCard = card(
    "Inputs and checks — chosen by AI",
    "ai",
    "AI",
    "rs-models",
    h("div", { class: "rs-field" }, h("span", { class: "rs-field-label", text: "Inputs" }), inputs),
    h("div", { class: "rs-field" }, h("span", { class: "rs-field-label", text: "Checks that will run" }), models),
    h(
      "p",
      { class: "rs-note" },
      "Picked for your question. Switch any off, or ",
      h("button", { class: "rs-link", type: "button", text: "open every setting", onclick: () => opts.openFull("method") }),
      ".",
    ),
  );

  /* ── Results ────────────────────────────────────────────────────────── */

  const results = h("div", { class: "rs-results" });
  renderEffect(() => {
    if (state.busy()) {
      results.replaceChildren(h("p", { class: "rs-empty", text: state.progress() || "Running…" }));
      return;
    }
    const report = state.report();
    if (report === null) {
      results.replaceChildren(
        h("p", {
          class: "rs-empty",
          text: "Run the research to see which check won, what the related assets added, and a plain explanation. Numbers appear only once they are measured.",
        }),
      );
      return;
    }
    const x = explainReport(
      report,
      state.question(),
      spec().context.map((c) => c.symbol),
      state.absent().filter((a) => !a.subject).map((a) => a.symbol),
    );
    results.replaceChildren(
      h("p", { class: "rs-verdict", text: x.verdict }),
      h("h3", { class: "rs-h3", text: "Which check won" }),
      h("p", { class: "rs-line", text: x.winner }),
      ...(x.contests.length > 1 ? [h("ul", { class: "rs-list" }, ...x.contests.map((c) => h("li", { text: c.text, "data-beat": String(c.beat) })))] : []),
      h("h3", { class: "rs-h3", text: "What the related assets added" }),
      h("ul", { class: "rs-list" }, ...x.related.map((t) => h("li", { text: t }))),
      ...(x.unanswered.length > 0 ? [pkWhy(x.unanswered.join(" "), `Could not answer (${x.unanswered.length})`)] : []),
      pkWhy(x.correction, "Why?"),
      h(
        "div",
        { class: "rs-decide" },
        h("button", { class: "sy-ghost", type: "button", text: "Keep this study", onclick: () => state.save() }),
        h("button", { class: "sy-ghost", type: "button", text: "See every number", onclick: () => opts.openFull("report") }),
      ),
    );
  });

  const resultsCard = card("Results", "both", "AI explains · you decide", "rs-out", results);

  return h(
    "div",
    { class: "rs-study" },
    h("div", { class: "rs-col" }, assetCard, questionCard, strictCard),
    h("div", { class: "rs-col" }, relatedCard, modelsCard, resultsCard),
  ) as HTMLElement;
}
