const APP_VER="14.6";
function collectConfig(store){const out={_meta:{app:'Mishel Intelligence Trading',ver:(typeof APP_VER!=='undefined'?APP_VER:''),exported:new Date().toISOString()},keys:{}};for(let i=0;i<store.length;i++){const k=store.key(i);if(k&&k.indexOf('mishel')===0)out.keys[k]=store.getItem(k)}return out}
function applyConfig(cfg,store){if(!cfg||!cfg.keys||typeof cfg.keys!=='object')return 0;let n=0;Object.keys(cfg.keys).forEach(k=>{if(k.indexOf('mishel')===0){store.setItem(k,cfg.keys[k]);n++}});return n}
function attributeConsensus(con){if(!con||!Array.isArray(con.votes)||!con.votes.length)return [];const V=con.votes.map(v=>({name:v.name,cat:v.cat,vote:+v.vote||0,w:+v.w||0}));const wsum=V.reduce((a,v)=>a+v.w,0)||1;const out=V.map(v=>({name:v.name,cat:v.cat,vote:v.vote,contribution:+(v.vote*v.w/wsum*100).toFixed(1)}));out.sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution));return out}
function explainBacktest(s){s=s||{};const strong=[],weak=[],notes=[];const num=v=>(v==null||!isFinite(v))?null:v;const tr=num(s.trades)||0,pf=num(s.pf),sh=num(s.sharpe),psr=num(s.psr),ror=num(s.ror),mdd=num(s.mdd),oos=num(s.oosR),is=num(s.isR);if(tr<20)notes.push('Only '+tr+' trades \u2014 too few to trust; treat as anecdotal until 30+.');if(pf!=null){if(pf>=1.5)strong.push('Profit factor '+pf.toFixed(2)+' \u2014 gross wins clearly exceed losses.');else if(pf<1)weak.push('Profit factor '+pf.toFixed(2)+' (<1) \u2014 loses money gross.')}if(sh!=null){if(sh>=1)strong.push('Per-trade Sharpe '+sh.toFixed(2)+' \u2014 smooth risk-adjusted returns.');else if(sh<0.3)weak.push('Low per-trade Sharpe ('+sh.toFixed(2)+') \u2014 noisy vs risk.')}if(psr!=null){if(psr>=0.9)strong.push('PSR '+(psr*100).toFixed(0)+'% \u2014 high confidence the edge is real, not luck.');else if(psr<0.6)weak.push('PSR only '+(psr*100).toFixed(0)+'% \u2014 could be selection luck.')}if(ror!=null){if(ror<=0.05)strong.push('Risk-of-ruin '+(ror*100).toFixed(0)+'% \u2014 survives resampling.');else if(ror>0.2)weak.push('Risk-of-ruin '+(ror*100).toFixed(0)+'% \u2014 a bad ordering could wipe you out.')}if(oos!=null&&is!=null){if(oos>0&&oos>=is*0.5)strong.push('Out-of-sample held up ('+oos.toFixed(1)+'R OOS vs '+is.toFixed(1)+'R IS).');else if(oos<=0)weak.push('Out-of-sample fell apart ('+oos.toFixed(1)+'R) \u2014 likely curve-fit.')}if(mdd!=null&&mdd>=40)weak.push('Deep max drawdown ('+mdd.toFixed(0)+'%) \u2014 hard to sit through.');let verdict;const sc=strong.length-weak.length;if(tr<20)verdict=['Insufficient evidence','muted'];else if(sc>=2&&pf!=null&&pf>=1.2)verdict=['Promising \u2014 forward-test before sizing up','up'];else if(sc<=-1||(pf!=null&&pf<1))verdict=['Weak \u2014 likely no real edge here','dn'];else verdict=['Mixed \u2014 needs more data or refinement',''];return {verdict,strong,weak,notes}}
function holderDelta(prev,cur){if(prev==null||cur==null||!isFinite(prev)||!isFinite(cur))return null;return +(cur-prev).toFixed(2)}
// sessionOf lives inline in the chart render; re-declared here for the unit test
function sessionOf(hh){const out=[];hh=((hh%24)+24)%24;if(hh>=0&&hh<9)out.push("asia");if(hh>=7&&hh<16)out.push("london");if(hh>=12&&hh<21)out.push("ny");return out}
module.exports={collectConfig,applyConfig,attributeConsensus,explainBacktest,holderDelta,sessionOf};
