/**
 * Where studies live between sessions, and the history each one accumulates.
 *
 * WHAT IS STORED AND WHAT IS NOT
 * The SPEC is stored, the SUMMARY of each run is stored, and the full report
 * is not. A report holds a lag profile per driver, every configuration of
 * every sweep and a correlation matrix; a dozen of those would fill the
 * browser's quota on their own, and `store/kv.ts` would start refusing writes
 * from the rest of the terminal. What is kept per run is the handful of
 * numbers the history is actually read from — the headline, the strength, the
 * count of what survived — and the report is regenerated by re-running the
 * spec, which is reproducible by construction.
 *
 * THE STRENGTH CARRIES ITS OWN NAME
 * A run reports one number the study is tracked by, and beside it the NAME of
 * what that number is. A deflated Sharpe and one-minus-an-adjusted-p are both
 * "about 0.7" and are not the same quantity. `readDecay` refuses a history
 * that mixes them, and it can only do that because the name is stored.
 */

import type { KV, Slot, WriteResult } from "../store/kv";
import type { StudySpec, HistoryYears } from "./spec";
import type { StudyReport } from "./run";
import type { Timings } from "./plan";
import { DEFAULT_SCHEDULE, type Schedule, type StrengthPoint } from "./schedule";

export interface RunSummary {
  readonly at: number;
  readonly ms: number;
  readonly headline: string;
  readonly rows: number;
  readonly hypotheses: number;
  readonly survivors: number;
  /** The one number this study is tracked by, or null when it produced none. */
  readonly strength: number | null;
  /** What that number IS. Never dropped — see the header. */
  readonly measure: string;
  readonly refusal: string | null;
}

export interface StudyRecord {
  readonly spec: StudySpec;
  readonly schedule: Schedule;
  readonly runs: readonly RunSummary[];
  /** Consecutive runs that produced nothing. Reset by any run that does. */
  readonly failures: number;
  /** Kept in the Library: a finding the operator chose to keep. */
  readonly filed: boolean;
}

/** Runs kept per study. Older ones fall off the front. */
export const RUN_HISTORY = 40;

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

const isYears = (v: unknown): v is HistoryYears =>
  v === "max" || (typeof v === "number" && Number.isFinite(v) && v > 0);

function isSpec(v: unknown): v is StudySpec {
  if (!isRecord(v)) return false;
  return (
    typeof v["id"] === "string" &&
    typeof v["name"] === "string" &&
    typeof v["symbol"] === "string" &&
    typeof v["timeframe"] === "string" &&
    Array.isArray(v["context"]) &&
    Array.isArray(v["methods"]) &&
    typeof v["horizon"] === "number" &&
    isYears(v["years"])
  );
}

/**
 * One stored study, validated.
 *
 * Deliberately shallow on `schedule` and `runs`: a missing schedule becomes
 * the default and a malformed run list becomes empty, because losing a
 * study's whole spec over a corrupted run summary is a worse outcome than
 * losing the history. The spec is the part that cannot be recomputed.
 */
export function isStudyRecord(v: unknown): v is StudyRecord {
  if (!isRecord(v)) return false;
  return isSpec(v["spec"]);
}

function normalise(v: StudyRecord): StudyRecord {
  return {
    spec: v.spec,
    schedule: isRecord(v.schedule) ? v.schedule : DEFAULT_SCHEDULE,
    runs: Array.isArray(v.runs) ? v.runs.filter((r) => isRecord(r) && typeof r["at"] === "number") : [],
    failures: typeof v.failures === "number" ? v.failures : 0,
    filed: v.filed === true,
  };
}

export const STUDIES_SLOT: Slot<StudyRecord[]> = {
  key: "studies",
  version: 1,
  fallback: () => [],
  /* Per item, so one corrupted study drops out alone rather than taking every
     other study with it — the rule `listSlot` exists for, written out here
     because each surviving item is also normalised. */
  validate: (v) => (Array.isArray(v) ? v.filter(isStudyRecord).map(normalise) : null),
};

export const TIMINGS_SLOT: Slot<Timings> = {
  key: "study-timings",
  version: 1,
  fallback: () => ({}),
  validate: (v) => {
    if (!isRecord(v)) return null;
    const out: Record<string, { msPerKRow: number; fixedMs: number; runs: number }> = {};
    for (const [k, raw] of Object.entries(v)) {
      if (!isRecord(raw)) continue;
      const perK = raw["msPerKRow"];
      const fixed = raw["fixedMs"];
      const runs = raw["runs"];
      if (typeof perK === "number" && typeof fixed === "number" && typeof runs === "number") {
        out[k] = { msPerKRow: perK, fixedMs: fixed, runs };
      }
    }
    return out;
  },
};

/**
 * The number a study is tracked by, and what it is.
 *
 * ORDER IS THE ARGUMENT. A deflated Sharpe is preferred because it is the only
 * figure here that has been penalised for the size of the search. Failing
 * that, one minus the smallest adjusted p-value — a real quantity, on a
 * different scale, which is exactly why its name travels with it. A study that
 * produced neither is tracked by nothing rather than by a number invented to
 * fill the column.
 */
export function strengthOf(report: StudyReport): { value: number | null; measure: string } {
  const s = report.correction.sharpe;
  if (s !== null && Number.isFinite(s.deflated)) {
    return { value: s.deflated, measure: "Deflated Sharpe per trade" };
  }
  const qs = report.correction.claims.map((c) => c.q).filter((q) => Number.isFinite(q));
  if (qs.length > 0) {
    return { value: 1 - Math.min(...qs), measure: "1 − smallest adjusted p" };
  }
  return { value: null, measure: "none" };
}

export function summarise(report: StudyReport): RunSummary {
  const { value, measure } = strengthOf(report);
  return {
    at: report.at,
    ms: report.ms,
    headline: report.headline,
    rows: report.rows,
    hypotheses: report.hypotheses,
    survivors: report.correction.survivors,
    strength: value,
    measure,
    refusal: report.refusal,
  };
}

/** The history `readDecay` reads, oldest first. */
export function strengthHistory(rec: StudyRecord): StrengthPoint[] {
  return rec.runs
    .filter((r): r is RunSummary & { strength: number } => typeof r.strength === "number")
    .map((r) => ({ at: r.at, value: r.strength, measure: r.measure }));
}

export function runsOnDay(rec: StudyRecord, now: number): number {
  const startOfDay = now - (now % 86_400_000);
  return rec.runs.filter((r) => r.at >= startOfDay).length;
}

export interface StudyStore {
  list(): readonly StudyRecord[];
  get(id: string): StudyRecord | null;
  save(rec: StudyRecord): WriteResult;
  remove(id: string): void;
  /** Append a run's summary and update the failure counter. */
  record(id: string, summary: RunSummary): WriteResult;
  /**
   * Drop a study's run history and keep the study.
   *
   * The spec is the part that cannot be recomputed; the runs can, by running
   * it again. The failure counter goes too — it counts runs, and there are
   * none. Returns how many runs went.
   */
  forgetRuns(id: string): number;
  timings(): Timings;
  setTimings(t: Timings): WriteResult;
  /** Fires whenever the stored list changes, including from another tab. */
  subscribe(fn: () => void): () => void;
}

export function createStudyStore(kv: KV): StudyStore {
  const read = (): StudyRecord[] => kv.get(STUDIES_SLOT);

  const put = (list: readonly StudyRecord[]): WriteResult => kv.write(STUDIES_SLOT, [...list]);

  return {
    list: read,

    get(id) {
      return read().find((r) => r.spec.id === id) ?? null;
    },

    save(rec) {
      const list = read();
      const i = list.findIndex((r) => r.spec.id === rec.spec.id);
      if (i < 0) return put([...list, rec]);
      return put(list.map((r, j) => (j === i ? rec : r)));
    },

    remove(id) {
      put(read().filter((r) => r.spec.id !== id));
    },

    record(id, summary) {
      const list = read();
      const i = list.findIndex((r) => r.spec.id === id);
      const existing = list[i];
      if (i < 0 || existing === undefined) {
        return { ok: false, reason: "unavailable", error: `No study with id ${id} is stored.` };
      }
      const runs = [...existing.runs, summary].slice(-RUN_HISTORY);
      /* A refusal is a failure for the guard's purposes and a RESULT for the
         history's. Both, not one or the other: the run is kept so the operator
         can see what it said, and the counter moves so a study whose vendor
         has gone away stops asking. */
      const failures = summary.refusal === null ? 0 : existing.failures + 1;
      return put(list.map((r, j) => (j === i ? { ...existing, runs, failures } : r)));
    },

    forgetRuns(id) {
      const list = read();
      const rec = list.find((r) => r.spec.id === id);
      if (rec === undefined || rec.runs.length === 0) return 0;
      const res = put(list.map((r) => (r.spec.id === id ? { ...r, runs: [], failures: 0 } : r)));
      return res.ok ? rec.runs.length : 0;
    },

    timings: () => kv.get(TIMINGS_SLOT),

    setTimings: (t) => kv.write(TIMINGS_SLOT, t),

    subscribe(fn) {
      return kv.subscribe((key) => {
        if (key === STUDIES_SLOT.key) fn();
      });
    },
  };
}
