function _val(name,arr,i){if(arr[name]!==undefined){const v=arr[name][i];return v==null?NaN:v}const n=+name;return Number.isFinite(n)?n:NaN}
function _triplet(t,arr,i){const [L,op,R]=t;const a=_val(L,arr,i),b=_val(R,arr,i);if(!Number.isFinite(a)||!Number.isFinite(b))return false;switch(op){case'>':return a>b;case'<':return a<b;case'>=':return a>=b;case'<=':return a<=b;case'crossabove':{const pa=_val(L,arr,i-1),pb=_val(R,arr,i-1);return a>b&&Number.isFinite(pa)&&Number.isFinite(pb)&&pa<=pb}case'crossbelow':{const pa=_val(L,arr,i-1),pb=_val(R,arr,i-1);return a<b&&Number.isFinite(pa)&&Number.isFinite(pb)&&pa>=pb}default:return false}}
function _group(g,arr,i){return Array.isArray(g)&&g.length?g.every(t=>_triplet(t,arr,i)):false}
function _stopPx(spec,arr,i,side,entry){const s=spec.stop||{type:'atr',mult:2};if(s.type==='atr'){const a=arr.atr[i]||entry*0.01;return entry-side*(s.mult||2)*a}if(s.type==='pct')return entry*(1-side*(s.value||1.5)/100);return entry*(1-side*0.015)}
function _tpPx(spec,entry,stop,side){const t=spec.tp;if(!t)return null;if(t.type==='rr')return entry+side*(t.value||2)*Math.abs(entry-stop);if(t.type==='pct')return entry*(1+side*(t.value||2)/100);return null}
function runStrategy(spec,d){
  const arr=indicatorsFor(d);const trades=[];let pos=null;const start=205;
  for(let i=start;i<d.length;i++){const px=d[i].c;
    if(pos){let exit=null,reason='';
      if(pos.side>0){if(d[i].l<=pos.stop){exit=pos.stop;reason='Stop-loss'}else if(pos.tp&&d[i].h>=pos.tp){exit=pos.tp;reason='Take-profit'}else if(_group(spec.exitLong,arr,i)){exit=px;reason='Exit rule'}}
      else{if(d[i].h>=pos.stop){exit=pos.stop;reason='Stop-loss'}else if(pos.tp&&d[i].l<=pos.tp){exit=pos.tp;reason='Take-profit'}else if(_group(spec.exitShort,arr,i)){exit=px;reason='Exit rule'}}
      if(exit!=null){const risk=Math.abs(pos.entry-pos.stop)||pos.entry*0.01;const R=(exit-pos.entry)*pos.side/risk;trades.push({...pos,exit,exitI:i,reason,R});pos=null}}
    if(!pos){if(_group(spec.long,arr,i)){const stop=_stopPx(spec,arr,i,1,px);pos={side:1,entry:px,entryI:i,stop,tp:_tpPx(spec,px,stop,1),entryReason:ruleText(spec.long)}}
      else if(spec.short&&_group(spec.short,arr,i)){const stop=_stopPx(spec,arr,i,-1,px);pos={side:-1,entry:px,entryI:i,stop,tp:_tpPx(spec,px,stop,-1),entryReason:ruleText(spec.short)}}}
  }
  return trades;
}
/* ---- readable rule rendering ---- */
const VNAME={close:'Close',open:'Open',high:'High',low:'Low',ema9:'EMA 9',ema20:'EMA 20',ema21:'EMA 21',ema50:'EMA 50',ema200:'EMA 200',rsi:'RSI(14)',atr:'ATR',macd:'MACD line',macds:'MACD signal',macdh:'MACD hist',stochk:'Stoch %K',stochd:'Stoch %D',cci:'CCI(20)',willr:'Williams %R',bbu:'Bollinger upper',bbl:'Bollinger lower',bbm:'Bollinger mid',stdir:'Supertrend dir',vwap:'VWAP',roc:'ROC(12)',adx:'ADX(14)',mfi:'MFI(14)',flux:'Kinetic Flux',div:'Divergence signal'};
const nv=x=>VNAME[x]!==undefined?VNAME[x]:x;
const OPN={'>':'&gt;','<':'&lt;','>=':'≥','<=':'≤',crossabove:'crosses above',crossbelow:'crosses below'};
function ruleText(g){return Array.isArray(g)&&g.length?g.map(([L,o,R])=>`${nv(L)} ${OPN[o]||o} ${nv(R)}`).join(' <span style="color:var(--muted2)">AND</span> '):'—'}
function stopText(s){if(!s)return '1.5% from entry';if(s.type==='atr')return `ATR × ${s.mult||2} (volatility-based)`;if(s.type==='pct')return `${s.value}% from entry`;return 'fixed'}
function tpText(t){if(!t)return 'exit rule only';if(t.type==='rr')return `${t.value}× the risk (R-multiple)`;if(t.type==='pct')return `${t.value}% from entry`;return '—'}
function renderRules(spec){
  const row=(k,v)=>`<tr><td style="width:120px;color:var(--muted);vertical-align:top">${k}</td><td>${v}</td></tr>`;
  document.getElementById('rulesPanel').innerHTML=`${spec.note?`<div style="background:var(--gold-dim);border:1px solid rgba(232,163,61,.3);border-radius:8px;padding:8px 11px;font-size:11px;color:var(--gold);margin-bottom:12px">${spec.note}</div>`:''}
  <table class="log" style="font-family:var(--ui)"><tbody>
    ${row('Enter long when',`<b class="up">${ruleText(spec.long)}</b>`)}
    ${spec.short?row('Enter short when',`<b class="dn">${ruleText(spec.short)}</b>`):''}
    ${row('Exit long when',ruleText(spec.exitLong)+' <span style="color:var(--muted2)">(or stop / target)</span>')}
    ${spec.short?row('Exit short when',ruleText(spec.exitShort)+' <span style="color:var(--muted2)">(or stop / target)</span>'):''}
    ${row('Stop-loss',stopText(spec.stop))}
    ${row('Take-profit',tpText(spec.tp))}
  </tbody></table>
  <div style="font-size:10.5px;color:var(--muted);margin-top:10px">Every trade in the log below is generated by these exact rules on the loaded data — nothing is hidden or fitted after the fact. Upload your own rules in Settings → they run through this same engine.</div>`;
}
/* ---- visual strategy editor (manually tweak rules and re-run) ---- */
const EDIT_VARS=['close','open','high','low','ema9','ema20','ema21','ema50','ema200','rsi','macd','macds','macdh','stochk','stochd','cci','willr','bbu','bbl','bbm','stdir','vwap','roc','adx','mfi','flux','div','atr'];
function _sel(cls,opts,val){return `<select class="${cls}" style="background:var(--panel);border:1px solid var(--edge);border-radius:6px;color:var(--txt);padding:4px 6px;font-size:11px">${opts.map(o=>`<option value="${o}"${o===val?' selected':''}>${cls==='ed-var'?(VNAME[o]||o):o}</option>`).join('')}</select>`}
function _rowHtml(t){t=t||['close','>','ema50'];return `<div class="ed-row" style="display:flex;gap:6px;margin-bottom:5px;align-items:center">${_sel('ed-var',EDIT_VARS,t[0])}${_sel('ed-op',['>','<','crossabove','crossbelow'],t[1])}<input class="ed-val" value="${t[2]}" style="width:90px;background:var(--panel);border:1px solid var(--edge);border-radius:6px;color:var(--txt);padding:4px 6px;font-family:var(--mono);font-size:11px" title="a number, or an indicator name"><button class="tbtn ed-del" style="padding:2px 8px">×</button></div>`}
function _groupHtml(label,key,arr,color){return `<div style="margin-bottom:10px"><div style="font-size:10px;color:${color};letter-spacing:.06em;text-transform:uppercase;margin-bottom:5px">${label}</div><div class="ed-group" data-key="${key}">${(arr||[]).map(t=>_rowHtml(t)).join('')}</div><button class="tbtn ed-add" data-key="${key}" style="padding:3px 9px;margin-top:2px">+ condition</button></div>`}
function renderEditor(spec){
  const st=spec.stop||{type:'atr',mult:2},tp=spec.tp||{type:'rr',value:2};
  document.getElementById('editorPanel').innerHTML=`
    <div class="grid2" style="align-items:start">
      <div>${_groupHtml('Enter long when','long',spec.long,'var(--bull)')}${_groupHtml('Exit long when','exitLong',spec.exitLong,'var(--muted)')}</div>
      <div>${_groupHtml('Enter short when','short',spec.short,'var(--bear)')}${_groupHtml('Exit short when','exitShort',spec.exitShort,'var(--muted)')}</div>
    </div>
    <div class="calc" style="grid-template-columns:1fr 1fr 1fr 1fr;margin-top:6px">
      <div class="field"><label>Stop type</label>${_sel('ed-stoptype',['atr','pct'],st.type)}</div>
      <div class="field"><label>Stop value</label><input id="edStopVal" class="mono" value="${st.mult||st.value||2}"></div>
      <div class="field"><label>TP type</label>${_sel('ed-tptype',['rr','pct','none'],tp.type||'none')}</div>
      <div class="field"><label>TP value</label><input id="edTpVal" class="mono" value="${tp.value||2}"></div>
    </div>
    <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap">
      <button class="run" id="edApply">Apply &amp; run ▷</button>
      <button class="tbtn" id="edReset">Reset to original</button>
      <button class="tbtn" id="edSave">★ Save as my strategy</button>
      <div style="font-size:10.5px;color:var(--muted);align-self:center">Right side of a condition can be a number (e.g. <span class="mono">70</span>) or another indicator (e.g. <span class="mono">ema200</span>).</div>
    </div>`;
  const ep=document.getElementById('editorPanel');
  ep.querySelectorAll('.ed-add').forEach(b=>b.onclick=()=>{const g=ep.querySelector(`.ed-group[data-key="${b.dataset.key}"]`);g.insertAdjacentHTML('beforeend',_rowHtml());bindDel(ep)});
  bindDel(ep);
  document.getElementById('edApply').onclick=()=>runBacktest(buildSpecFromEditor());
  document.getElementById('edReset').onclick=()=>{const nm=document.getElementById('stratSel').value;renderEditor(specFor(nm,CURSTYLE));runBacktest()};
  document.getElementById('edSave').onclick=()=>{const spec2=buildSpecFromEditor();const nm=prompt('Name your strategy:',(document.getElementById('stratSel').value||'My strategy')+' (tweaked)');if(!nm)return;spec2.name=nm;spec2.style='custom';addUserStrat(spec2);toast('★ Saved: '+nm,var_bull());const b=document.getElementById('btStyle');b.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x.dataset.style==='custom'));populateStrats('custom');document.getElementById('stratSel').value=nm;runBacktest()};
}
function bindDel(ep){ep.querySelectorAll('.ed-del').forEach(b=>b.onclick=()=>b.closest('.ed-row').remove())}
function buildSpecFromEditor(){
  const ep=document.getElementById('editorPanel');const spec={name:document.getElementById('stratSel').value+' (tweaked)',style:CURSTYLE};
  ['long','short','exitLong','exitShort'].forEach(key=>{const g=ep.querySelector(`.ed-group[data-key="${key}"]`);const rows=[...g.querySelectorAll('.ed-row')].map(r=>[r.querySelector('.ed-var').value,r.querySelector('.ed-op').value,r.querySelector('.ed-val').value.trim()]).filter(t=>t[2]!=='');if(rows.length)spec[key]=rows});
  const stType=ep.querySelector('.ed-stoptype').value,stVal=+document.getElementById('edStopVal').value||2;spec.stop=stType==='atr'?{type:'atr',mult:stVal}:{type:'pct',value:stVal};
  const tpType=ep.querySelector('.ed-tptype').value,tpVal=+document.getElementById('edTpVal').value||2;spec.tp=tpType==='none'?null:{type:tpType,value:tpVal};
  return spec;
}
/* ---- spec library: named strategies → transparent rules ---- */
function specFor(name,style){
  if(USER_STRATS[name])return USER_STRATS[name].spec;
  const n=name.toLowerCase();const atr2={type:'atr',mult:2},rr2={type:'rr',value:2},rr15={type:'rr',value:1.5};let s;
  if(/williams|willr/.test(n))s={long:[['willr','crossabove','-80']],short:[['willr','crossbelow','-20']],exitLong:[['willr','>','-30']],exitShort:[['willr','<','-70']],stop:atr2,tp:rr2,note:'Williams %R reversal — buys as %R climbs out of oversold, sells as it drops out of overbought.'};
  else if(/\broc\b|impulse|rate.of.change/.test(n))s={long:[['roc','crossabove','0'],['close','>','ema50']],short:[['roc','crossbelow','0'],['close','<','ema50']],exitLong:[['roc','<','0']],exitShort:[['roc','>','0']],stop:atr2,tp:rr2,note:'Rate-of-change impulse in the trend direction (filtered by the EMA50).'};
  else if(/adx|trend.strength/.test(n))s={long:[['adx','>','25'],['ema9','>','ema21'],['close','>','ema50']],short:[['adx','>','25'],['ema9','<','ema21'],['close','<','ema50']],exitLong:[['ema9','crossbelow','ema21']],exitShort:[['ema9','crossabove','ema21']],stop:atr2,tp:rr2,note:'Only trades when ADX confirms a real trend (>25); exits on the fast/slow EMA cross.'};
  else if(/mfi|money.flow/.test(n))s={long:[['mfi','crossabove','20']],short:[['mfi','crossbelow','80']],exitLong:[['mfi','>','55']],exitShort:[['mfi','<','45']],stop:atr2,tp:rr2,note:'Money Flow Index reversal — volume-weighted oversold/overbought.'};
  else if(/ribbon|triple.ema/.test(n))s={long:[['ema9','>','ema21'],['ema21','>','ema50'],['close','crossabove','ema9']],short:[['ema9','<','ema21'],['ema21','<','ema50'],['close','crossbelow','ema9']],exitLong:[['close','<','ema21']],exitShort:[['close','>','ema21']],stop:atr2,tp:rr2,note:'Triple-EMA ribbon — enters only when 9>21>50 (or inverse) confirms stacked trend.'};
  else if(/9\/21/.test(n))s={long:[['ema9','crossabove','ema21'],['close','>','ema9']],short:[['ema9','crossbelow','ema21']],exitLong:[['close','<','ema21']],exitShort:[['close','>','ema21']],stop:atr2,tp:rr15};
  else if(/50\/200/.test(n))s={long:[['ema50','>','ema200'],['close','crossabove','ema50']],short:[['ema50','<','ema200'],['close','crossbelow','ema50']],exitLong:[['close','<','ema50']],exitShort:[['close','>','ema50']],stop:atr2,tp:rr2};
  else if(/supertrend/.test(n))s={long:[['stdir','crossabove','0']],short:[['stdir','crossbelow','0']],exitLong:[['stdir','<','0']],exitShort:[['stdir','>','0']],stop:atr2,tp:{type:'rr',value:3}};
  else if(/macd/.test(n))s={long:[['macd','crossabove','macds'],['macdh','>','0']],short:[['macd','crossbelow','macds']],exitLong:[['macd','crossbelow','macds']],exitShort:[['macd','crossabove','macds']],stop:atr2,tp:rr2};
  else if(/rsi/.test(n))s={long:[['rsi','crossabove','32']],short:[['rsi','crossbelow','68']],exitLong:[['rsi','>','55']],exitShort:[['rsi','<','45']],stop:{type:'pct',value:1.5},tp:rr2,note:'Mean-reversion: buy oversold, sell overbought.'};
  else if(/stochastic/.test(n))s={long:[['stochk','crossabove','stochd'],['stochk','<','40']],short:[['stochk','crossbelow','stochd'],['stochk','>','60']],exitLong:[['stochk','>','80']],exitShort:[['stochk','<','20']],stop:{type:'pct',value:1},tp:rr15};
  else if(/cci/.test(n))s={long:[['cci','crossabove','-100']],short:[['cci','crossbelow','100']],exitLong:[['cci','>','120']],exitShort:[['cci','<','-120']],stop:atr2,tp:rr2};
  else if(/vwap/.test(n))s={long:[['close','crossabove','vwap']],short:[['close','crossbelow','vwap']],exitLong:[['close','<','vwap']],exitShort:[['close','>','vwap']],stop:{type:'pct',value:0.8},tp:rr15,note:'Trades continuation/reversion around the session VWAP.'};
  else if(/breakout/.test(n))s={long:[['close','crossabove','bbu']],short:[['close','crossbelow','bbl']],exitLong:[['close','<','bbm']],exitShort:[['close','>','bbm']],stop:atr2,tp:rr2,note:/session|opening|london/.test(n)?'Proxy: a volatility-band breakout stands in for the session/opening range.':''};
  else if(/fade|grid|mean.rev|stat.arb|liquidity.prov|avellaneda|order.flow|gamma|basis|twap/.test(n))s={long:[['close','crossbelow','bbl']],short:[['close','crossabove','bbu']],exitLong:[['close','>','bbm']],exitShort:[['close','<','bbm']],stop:{type:'pct',value:1.2},tp:{type:'pct',value:1.0},note:/avellaneda|order.flow|gamma|basis|twap|liquidity|stat.arb/.test(n)?'Simplified model — true market-maker/quant logic needs order-book & funding data; this captures the mean-reversion core it rests on.':'Fade band extremes back toward the mean.'};
  else if(/liquidity sweep|pdh|pdl|fvg|double|weekly|s\/r/.test(n))s={long:[['close','crossbelow','bbl'],['rsi','<','42']],short:[['close','crossabove','bbu'],['rsi','>','58']],exitLong:[['close','>','bbm']],exitShort:[['close','<','bbm']],stop:atr2,tp:rr2,note:'Proxy for the SMC pattern using band + RSI extremes (real build uses the actual FVG/level detectors).'};
  else if(/flux|kinetic/.test(n))s={long:[['flux','crossabove','0'],['adx','>','18']],short:[['flux','crossbelow','0'],['adx','>','18']],exitLong:[['flux','<','0']],exitShort:[['flux','>','0']],stop:atr2,tp:rr2,note:'Kinetic Flux = normalized price-velocity × volume participation (open interpretation). Positive = bullish energy; ADX filters for trend strength.'};
  else if(/divergence/.test(n))s={long:[['div','>','0']],short:[['div','<','0']],exitLong:[['rsi','>','62']],exitShort:[['rsi','<','38']],stop:atr2,tp:rr2,note:'Enters on detected RSI divergence — transparent price-vs-RSI swing comparison, not a hidden signal.'};
  else if(/momentum|rotation|dual/.test(n))s={long:[['ema50','>','ema200'],['rsi','>','55']],short:[['ema50','<','ema200'],['rsi','<','45']],exitLong:[['rsi','<','48']],exitShort:[['rsi','>','52']],stop:atr2,tp:{type:'rr',value:3}};
  else s=style==='swing'?{long:[['ema50','>','ema200'],['close','crossabove','ema50']],short:[['ema50','<','ema200'],['close','crossbelow','ema50']],exitLong:[['close','<','ema50']],exitShort:[['close','>','ema50']],stop:atr2,tp:rr2}:{long:[['close','crossabove','vwap']],short:[['close','crossbelow','vwap']],exitLong:[['close','<','vwap']],exitShort:[['close','>','vwap']],stop:{type:'pct',value:1},tp:rr15};
  s.name=name;s.style=style;return s;
}

/* ---------- uploaded strategies ---------- */
const USER_STRATS={};
const EXAMPLE_SPEC={name:"My RSI + Trend",style:"swing",long:[["ema50",">","ema200"],["rsi","crossabove","40"]],short:[["ema50","<","ema200"],["rsi","crossbelow","60"]],exitLong:[["rsi",">","65"]],exitShort:[["rsi","<","35"]],stop:{type:"atr",mult:2},tp:{type:"rr",value:2},note:"Uploaded example."};
const PY_EXAMPLE=`# Mishel Intelligence Trading strategy — the terminal reads the STRATEGY dict below.
# Each condition is [indicator, operator, value]. All conditions in a list are AND-ed.
# Operators: ">", "<", "crossabove", "crossbelow"
# Indicators: close open high low ema9 ema20 ema21 ema50 ema200 rsi macd macds
#   macdh stochk stochd cci willr adx roc mfi flux vwap bbu bbl bbm stdir atr div
# stop.type: "atr" (mult) or "pct" (value).  tp.type: "rr" (value) or "pct" (value) or omit.

STRATEGY = {
    "name": "My Python Strategy",
    "style": "swing",                       # scalp | intraday | swing | mm | custom
    "long":  [["ema50", ">", "ema200"], ["rsi", "crossabove", "40"]],
    "short": [["ema50", "<", "ema200"], ["rsi", "crossbelow", "60"]],
    "exitLong":  [["rsi", ">", "65"]],
    "exitShort": [["rsi", "<", "35"]],
    "stop": {"type": "atr", "mult": 2},
    "tp":   {"type": "rr",  "value": 2},
}
`;
